title = "Dave Husen"
baseURL = "https://davehusen.com"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = "G-22C973FM91"  # add your tracking id

[params]
  author = "Dave Husen"
  #description = "A simple monospaced resume theme for Hugo."
  #favicon = "favicon.ico"  # path to a .ico to use as favicon
  #logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "© Dave Husen"
    url = "https://davehusen.com"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "'Inter', sans-serif"
    fontFamilyMono = "'JetBrains Mono', monospace"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/davehusen"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = 'Github'
    url = "https://github.com/davehusen"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = 'LinkedIn'
    url = "https://www.linkedin.com/in/davehusen"
  [[params.socialIcons]]
    icon = "fas fa-paper-plane"
    title = "E-mail"
    url = "mailto:dave@davehusen.com"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "about"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "bookshelf"
    url = "/bookshelf"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
